### ISSUE TITLE
Busca de Mappers de LN

### ISSUE THREAD

**Issue by TalissonFV** [TalissonFV/TorneioX#1]
Precisamos entrar em contatos com os mappers sugeridos na reunião do dia 18/09/2023.

Segue a lista:

- Mappers LN:

- [x] Hylotl
- [x] Mikuaimbot
- [x] Logan636
- [ ] FelixSpade
- [x] TiagoLimaX
- [x] Amerom

**Comment by angelismarc** [comment]
que ódioooooooooooooooooooooooooooooooooooooo
